ftest/urls.py
from django.urls import path
from . import views

app_name = 'ftest'

urlpatterns = [
    path('', views.index, name='home'),
    path('confirm/', views.confirm, name='confirm')
]

functest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ftest.urls')),
]

ftest/models.py
from django.db import models

# Create your models here.

class Message(models.Model):
	name = models.CharField(max_length=50)
	message = models.CharField(max_length=100)
	date = models.DateTimeField(auto_now_add=True)
	
	def __str__(self):
		return '%s' % self.message

ftest/forms.py
from django.forms import ModelForm
from .models import Message

class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = '__all__'

ftest/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .forms import MessageForm
from .models import Message

# Create your views here.

data_list = [{}]

def index(request):
	if request.method == 'POST':
		form = MessageForm(request.POST)
		data_list[0]["name"] = request.POST.get("name")
		data_list[0]["message"] = request.POST.get("message")

		if form.is_valid():
			return redirect("/confirm/")
		else:
			return render(request, 'homepage.html', {"data":Message.objects.all()})

	else:
			return render(request, 'homepage.html', {"data":Message.objects.all()})


def confirm(request):
	if request.method == 'POST':
		form = MessageForm(request.POST)
		form.save()
		return redirect("/")
	else:
		return render(request, 'confirm.html', {"data_list" : data_list})

ftest/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">

    <body class="background">

        <head>
            
            <!-- Required meta tags -->
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

            <!-- Bootstrap CSS -->
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

            <!-- Font Link -->
            <link href="https://fonts.googleapis.com/css?family=Playfair+Display&display=swap" rel="stylesheet">

            <!-- CSS Link -->
            <link  rel=stylesheet href="{% static 'style.css' %}">

        </head>

        {% block content %}{% endblock %}

    </body>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</html>

ftest/templates/confirm.html
{% extends "base.html" %}
{% load static %}

{% block content %}

    <div class="container">

        <div class="confirmation">
            <h1>CONFIRM MESSAGE</h1>
        </div>

        <div>


            {% for data in data_list %}
            <form method="POST">
            
                {% csrf_token %}
                <p class="pending">
                    name: {{ data.name }}
                </p>

                <p class="pending">
                    message: {{ data.message }}
                </p>

                <input type="hidden" id="name" name="name" value="{{ data.name }}">
                <input type="hidden" id="message" name="message" value="{{ data.message }}">
                
                <button type="submit" class="btn btn-primary bg-dark shadow-none conf-button" data-toggle="button" aria-pressed="false" name="submit-button">
                    CONFIRM
                </button>

                <a href="{% url 'ftest:home' %}">
                    <button type="button" class="btn btn-primary bg-dark shadow-none back-button" data-toggle="button" aria-pressed="false">
                        GO BACK
                    </button>
                </a>

            </form>
            {% endfor %}

        </div>

    </div>

{% endblock %}

ftest/templates/homepage.html
{% extends "base.html" %}
{% load static %}

{% block content %}

    <div class="container">
        
        <div class="col-sm text-center welcome">
            <h1>WELCOME</h1>
        </div>

        <div class="col-sm pour">
            Pour your thoughts here!
        </div>

        <div>

            <form method="POST" action="">

                    <div class="input-group mb-3">
                        
                        {% csrf_token %}
                        <input type="text" class="form-control form-color" placeholder="What's on your mind..."
                        aria-label="Recipient's message" name="message" maxlength="100">

                    </div>

                    <div class="input-group mb-3">

                        <input type="text" class="form-control form-color" placeholder="Your name here..."
                        aria-label="Recipient's username" name="name" maxlength="50">

                        <div class="input-group-append">

                            <button class="btn submit-button" type="submit" value="Submit" name="submit">
                                POST!
                            </button>
                            
                        </div>

                    </div>
                    
            </form> 

        </div>


        <div class="row">

            {% for data in data %}

            <div class="col-sm-6 col-md-auto message-card text-center">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ data.message }}</h5>
                        <p class="card-text">{{ data.name }} {{ data.date }}</p>
                    </div>
                </div>
            </div>
            
            {% endfor %}

        </div>

    </div>

{% endblock %}